services:

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: employee_db

    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

    networks:
      - twotier-network

  web:
    build: .
    container_name: flask-app
    restart: always

    ports:
      - "5000:5000"

    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: employee_db
      SECRET_KEY: employee-complaint-secret-key

    depends_on:
      - db

    networks:
      - twotier-network

volumes:
  mysql_data:

networks:
  twotier-network:
    driver: bridge