apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-app
  labels:
    app: employee-app
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30005
