containers:
  - name: mysql
    image: mysql:5.7

    ports:
      - containerPort: 3306

    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD

      - name: MYSQL_DATABASE
        value: employee_db

    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "512Mi"

    volumeMounts:
      - name: mysql-storage
        mountPath: /var/lib/mysql
