apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: employee-app
  labels:
    app: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:5.7

          ports:
            - containerPort: 3306

          args:
            - "--performance-schema=OFF"
            - "--innodb-buffer-pool-size=64M"
            - "--max-connections=20"

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: employee_db

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

